### ISSUE TITLE
Is it possible to change positioning/placing objects like in iOS?

### ISSUE THREAD

**Issue by PepaZapletal** [SceneView/sceneform-android#174]
This is only a quick question:

Is it possible to change positioning/placing objects like in iOS? Instead of white dots (symboling flat surface) use some things like this

![ios](https://user-images.githubusercontent.com/55383847/135826222-2f310f71-cc3d-47c6-bccc-6135cc270a19.jpg)
:

**Comment by ThomasGorisse** [comment]
This is will be available with Instant Placement soon but as I mentioned here [We need sponsoring to continue...](https://github.com/ThomasGorisse/sceneform-android-sdk#we-need-sponsoring-to-continue) it will be kept private until we get enough sponsoring because we spend one year of days and nights working on this repos instead of making paying apps with a result of $0 sponsoring.

**Comment by RGregat** [comment]
As Thomas said, there is no public in-build method available yet. You can try to implement something by yourself, but I have to say that it is maybe not 100% what you are looking for. 

* Constantly do a HitTest on all available (or a subset of) ARCore TrackingTypes. (hint use the screen center)
* Do something with the result. Show a ViewRenderable or a gltf model at the HitResult position. Use normal Android-Layout Buttons or include it in your ViewRenderable/gltf model. 
* Interact with the Buttons

Of course there is alot more to consider, you see I'm very vague here. By the way, Instant Placement can give you some more possibilities. 
To be honest I would prefer a in-build variant, but as Thomas already said, we need some support.
