### ISSUE TITLE
There is a memory leak, How to really release graphics resources

### ISSUE THREAD

**Issue by brady2037** [SceneView/sceneform-android#206]
Load the following model：
[machine_tool.glb(80.2MB)](https://lance-img.nos-eastchina1.126.net/file/machine_tool.glb)

Using **ar-model-viewer-java** in the project，replace model.
Add the model to the arfragment page and finish，Don't exit app. The graphic resources are not released.

[![memory.png](https://i.postimg.cc/HxgsSphD/memory.png)](https://postimg.cc/HJ6gnCmB)

Reproduction steps：
1. Create a new entry class to jump
[![code-example.png](https://i.postimg.cc/J4pYTGvZ/code-example.png)](https://postimg.cc/Czf45LFx)
2. Run and Open the MainActivity, add the model in screen, return to  RouterActivity
3. Check  Profile tool -> Memory ->  Graphics 

OutOfMemory will appear if repeated multiple times
[![outofmemorypicture.png](https://i.postimg.cc/N0kMcrrj/outofmemorypicture.png)](https://postimg.cc/LqhRk5Tc)

**Comment by RGregat** [comment]
I'll check this in the next view days. What I know is, that the ArSession is not released immediately and therefore it could be, that the resources are not released. You can try to release the ArSession by yourself. You can access the Session through ArSceneView and call destroySession. To be fair it is not really a SceneForm issue but a lifecycle issue. The function onDestroy can be called couple of seconds later after the view is dismissed. That's it for now, I look further into this topic the next days!

**Comment by brady2037** [comment]
> I'll check this in the next view days. What I know is, that the ArSession is not released immediately and therefore it could be, that the resources are not released. You can try to release the ArSession by yourself. You can access the Session through ArSceneView and call destroySession. To be fair it is not really a SceneForm issue but a lifecycle issue. The function onDestroy can be called couple of seconds later after the view is dismissed. That's it for now, I look further into this topic the next days!

Thank you very much for your recovery!  I'm looking for a way to really release graphics resources.
Call ArSceneView->destroySession(), It doesn't work, destrorySession() has been indirectly called in BaseArFragment:
BaseArFragment->onDestroy()->destroy()->arSceneView.destroy()->ArSceneView.destroySession()

**Comment by niloofari** [comment]
I have the same issue. I'm using .glb object format and they are not being released at all. I found SceneView.destroyAllResources(); as one command that originally gets into the renderer.java class of the sceneform library. In the code bellow you see that two functions are called:  ResourceManager.getInstance().destroyAllResources(); and EngineInstance.destroyEngine();
The first one tries to access the registry for rendering features which is referred as "resourceHolders" and release all the resources. The second one shuts down the engine and terminates the app. I altered the code to just call the first function without destroying the engine (commented this line) to see if the graphical mem is released but unfortunately nothing changed. The graphical mem is released only when we close the app. Is this problem related to the object type, i.e., because I'm using .glb file?

public static void destroyAllResources() {

    ResourceManager.getInstance().destroyAllResources();
   EngineInstance.destroyEngine();

  }



public void destroyAllResources() {
   for (ResourceHolder resourceHolder : resourceHolders) {
  resourceHolder.destroyAllResources();}

**Comment by brady2037** [comment]
> I have the same issue. I'm using .glb object format and they are not being released at all. I found SceneView.destroyAllResources(); as one command that originally gets into the renderer.java class of the sceneform library. In the code bellow you see that two functions are called: ResourceManager.getInstance().destroyAllResources(); and EngineInstance.destroyEngine(); The first one tries to access the registry for rendering features which is referred as "resourceHolders" and release all the resources. The second one shuts down the engine and terminates the app. I altered the code to just call the first function without destroying the engine (commented this line) to see if the graphical mem is released but unfortunately nothing changed. The graphical mem is released only when we close the app. Is this problem related to the object type, i.e., because I'm using .glb file?
> 
> public static void destroyAllResources() {
> 
> ```
> ResourceManager.getInstance().destroyAllResources();
> ```
> 
> EngineInstance.destroyEngine();
> 
> }
> 
> public void destroyAllResources() { for (ResourceHolder resourceHolder : resourceHolders) { resourceHolder.destroyAllResources();}


`EngineInstance.destroyEngine();` It is useful
[![Snipaste-2021-11-30-10-14-36.png](https://i.postimg.cc/m2JcQPCz/Snipaste-2021-11-30-10-14-36.png)](https://postimg.cc/QHgxDx6h)

I think it may be because `EngineInstance` statically holds the `filament.Engine`reference
 But there is a problem,How to reinitialize,I found `EngineInstance.getEngine();` , But it didn't work,

**Comment by weijiaqi** [comment]
@brady2037  How to reinitialize, are you done?

**Comment by kustraslawomir** [comment]
anyone? :(

**Comment by Sumit-Pise** [comment]
Is any solution here ?

**Comment by ThomasGorisse** [comment]
You should move to SceneView
