### ISSUE TITLE
Can we lose reference to Sceneform and ARCore objects like Node, Pose, HitTest etc. when the frame updates?

### ISSUE THREAD

**Issue by sarimmehdi** [SceneView/sceneform-android#223]
Hello. Let me describe the situation. I am using Dagger 2 to do dependency injection and I have a view model that is responsible for interacting with the ArSceneView whenever an interaction with the SQLite database takes place. 

I have a class (**keepTrackOfObjects.java**) that keeps track of the latest Frame, HitTest, and AnchorNode object. 

I have a separate class (**takeUserInputAndInteractWithSqlite.java**) that takes user input (tap on the screen) and adds an object to the SQLite database. This object contains information regarding the anchor that is then created by the view model when it observes a change take place. When the user taps on the screen, I get a HitTestResult object and I do keepTrackOfObjects.setHitTestResult(hitTestResult)

Inside the **MainActivity.java**'s onUpdateFrame function, I set the latest Frame using keepTrackOfObjects.setFrame(frame)

So, that means I have both the latest Frame object and the HitTestResult object. But, inside my view model's observe function (which is triggered when I add a new object to the SQLite database), both these objects are null. 

Does that mean I lose reference to Sceneform/ ARCore objects whenever there is a frame update? Is there a way to keep track of the ARCore and Sceneform objects then?

**Comment by sarimmehdi** [comment]
Okay upon more investigation, it seems to be an issue with dagger 2, since doing manual dependency injection doesn't cause this. But I will investigate it a bit more before closing

**Comment by sarimmehdi** [comment]
So, I should not keep track of Frame but of items that I need from Frame? Is there a guideline for this? As in, what objects from ARCore and Sceneform I can keep track of and what I can't?

**Comment by sarimmehdi** [comment]
So, I am closing this issue since it had nothing to do with Sceneform but with how I was using Dagger 2.

**Comment by RGregat** [comment]
> So, I should not keep track of Frame but of items that I need from Frame? Is there a guideline for this? As in, what objects from ARCore and Sceneform I can keep track of and what I can't?

That is true, don't keep anything from the `Frame`. Every `Frame` should be handled as a throw away object. 
Same story for any coordinate you can request from a `Node`, don't save same, because the values will change during the session.  
The `PointCloud` you can get from a `Frame` is somehow unique as well, but every point has an id, which in theory can be used to update the position of a particular point on multiple `Frames`. But I would suggest another approach to keep track of PointCloud-Points. 

If you want to save anything in a SQLite-Database do it right before you close the AR-View.
