### ISSUE TITLE
Can we change the orientation/axis ? (Question)

### ISSUE THREAD

**Issue by akunerio** [SceneView/sceneform-android#323]
![orientation](https://user-images.githubusercontent.com/1333372/155298158-4e3c847a-39fa-4649-95af-f135a8fb66df.jpg)

Usually, when we load the asset with TransformableNode the orientation axis will be in the middle of the asset.
Can we change the orientation axis from the normal to the corner shown in the picture above?
It is because when we change the set rotation and set the scale always consistent in the middle. 
I hope the orientation can be changed into the corner, so we can rotate from the corner, not from the middle.

Thank you.

**Comment by RGregat** [comment]
Good question, 
to be fair I'm just guessing for now. But we had a similar discussion a few weeks ago https://github.com/SceneView/sceneform-android/discussions/279 The problem was a little bit different, but the questions sounds similar. A direct update of the origin of the 3D-Model is not possible as far as I know, but you can get the BBox of your model https://github.com/google/filament/blob/main/android/filament-android/src/main/java/com/google/android/filament/Box.java and https://github.com/SceneView/sceneform-android/discussions/243#discussioncomment-1832858 and calculate the offset from the current anchored-position of your modell to your prefered position. If you have it, add the translation values in x, y and z to your node (not the transformable node).  
Very rough explained, I know. If it is enough for you to implement something, share the result please. If not we/me try to be more detailled :)

**Comment by ThomasGorisse** [comment]
This is possible and very simple within [SceneView](https://github.com/SceneView/sceneview-android) by changing the model origin to align your model position within a Node:
https://github.com/SceneView/sceneview-android/blob/9b3feb24b5876f074ecb23afa7852262f767d26f/sceneview/src/main/kotlin/io/github/sceneview/node/ModelNode.kt#L31
And then just apply the rotation to the node itself, not the model.

You can also align the node model from its bounding box at the glb loading time with the coming push `centerOrigin` wich defines the point from where your model is anchored (not only an AR term) in the node:
```kotlin
loadModel(
    ...
    centerOrigin = Position(x = 0, y = -1.0f, z = 0.0f)
)
```
Here, if the node is at screen center, the model will be displayed above the center.
Same if you rotate the node (`node.rotation` not the `node.modelRotation`, the axis will be the node one so it will do what you are looking for.

**Comment by akunerio** [comment]
Interesting, but I still cannot call the loadModel function.
Which place do I need to call and set the model with loadModel in the example?

![image](https://user-images.githubusercontent.com/1333372/155470495-7635fcce-8880-457a-8b74-90d8036d3db7.png)

**Comment by ThomasGorisse** [comment]
You are welcome.
Please consider sponsoring us if you are happy with SceneView.
