### ISSUE TITLE
native anr occur

### ISSUE THREAD

**Issue by chenleicrm** [SceneView/sceneform-android#340]
I have get three native anr trace files in below zip files using 1.20.5 and need your help @ThomasGorisse 

[anr.zip](https://github.com/SceneView/sceneform-android/files/8244528/anr.zip)

**Comment by chenleicrm** [comment]
I try to repeat pause and resume actions just like lock phone screen and unlock . phone is going to be hot and running slow. but app memory is normal . i wonder to know why this happens @ThomasGorisse

**Comment by ThomasGorisse** [comment]
I have no other answer than: Move to [SceneView ](https://github.com/SceneView/sceneview-android) in order to have an Activity Lifecycle aware memory management. Even the screen lock (Allow or not the screen auto off) is handled in case of ARCore currently tracking or not. Meaning if you put your phone on a desk, the screen lock timeout will be enabled. At the opposite of when you are currently tracking AR.

**Comment by chenleicrm** [comment]
Is SceneView support transform now ?

**Comment by ThomasGorisse** [comment]
https://github.com/SceneView/sceneview-android/pull/38

**Comment by chenleicrm** [comment]
I will try this branch
