### ISSUE TITLE
I don't understand why there has to call updateBoneMatrices in updateRegionNodes

### ISSUE THREAD

**Issue by dandingol03** [SceneView/sceneform-android#374]
Hi. I want to implement a skeleton-binding feature in `filament` recently, and i saw the discussion you post on filament repo. There are some interesting sample on this `sceneform-android ` repo, and i dive to the `argument-face` sample. I found some weried code as below:
```
 if(faceRegionNode != null && faceRegionNode.getRenderableInstance() != null) {
      faceRegionNode.getRenderableInstance().getFilamentAsset().getAnimator().updateBoneMatrices();
  }
```
**Question**:
The `fox.glb` has no skin at all, is there any reason tø call `updateBoneMatrices`?Here is the code of `updateBoneMatrices`:
```
void Animator::updateBoneMatrices() {
    auto renderableManager = mImpl->renderableManager;
    auto transformManager = mImpl->transformManager;

    auto update = [=](const SkinVector& skins, BoneVector& boneVector, utils::NameComponentManager* nameComponentManager) {
        for (const auto& skin : skins) {
            ....
       }
}
```
Because there is no skin in  `fox.glb`, this function cannot go to the `update` lambda in function. I delete this function invoking , and the `argument-face` sample still work. I want to know why, thanks.

**Comment by ThomasGorisse** [comment]
Hi,
Sorry for the late answer but we are pretty more active within [the new Kotlin repo](https://github.com/SceneView/sceneview-android).
You're totally right about the double `updateBoneMatrices` call.

Since you look like having some Filament knowledge would you like helping us on moving and cleaning the AugmentedFaceNode to Kotlin within [SceneView](https://github.com/SceneView/sceneview-android)?

**Comment by dandingol03** [comment]
Maybe someday i am free. Recently filament repo release attach-bone
interface, i am trying to implement the bone attach function with that
interface. I still have some problem on that.
