### ISSUE TITLE
The video in augmented-images sample is mirrored

### ISSUE THREAD

**Issue by giandifra** [SceneView/sceneform-android#437]
Hello, I'm trying the sample about augmented images, the video displayed is mirrored. Is there a solution for this? 
I tried to play with rotation `Quaternion.axisAngle(Vector3(0f, 1f, 0f), 180f)` without good results. 

Thanks

**Comment by kustraslawomir** [comment]
@giandifra 
```
val videoNode = TransformableNode(arFragment.transformationSystem).apply {
                    localRotation = Quaternion.axisAngle(Vector3(-1f, 0f, 0f), 180f)
                }
```

**Comment by jocmp** [comment]
For posterity, I ran into a similar issue. To solve the flipped image I called `flipUV(false)` on the material based on [the Filament documentation](https://google.github.io/filament/Materials.html#materialdefinitions/materialblock/general:flipuv).

The washed out image maybe caused by an incorrect tonemap. The solve there is to call `inverseTonemapSRGB` on the video texture's base color.

```kotlin
.material(
  """
  void material(inout MaterialInputs material) {
    prepareMaterial(material);
    material.baseColor = texture(materialParams_videoTexture, getUV0()).rgba;
    material.baseColor.rgb = inverseTonemapSRGB(material.baseColor.rgb);
  }
  """.trimIndent()
)
```

Full code for this can be found in a project I maintain here: https://github.com/gvsucis/art-at-gvsu-android/pull/33
